export { default as Home } from './home';
export { default as WebCourses } from './courses';
export { default as DetailCourseWeb } from './courses/Detail';
export { default as MyCourses } from './courses/MyCourses';
export { default as Learning } from './courses/Learning';
export { default as WebPosts } from './posts';
export { default as DetailPostWeb } from './posts/Detail';
export { default as MyPosts } from './posts/MyPosts';
export { default as Personal } from './personal';
